runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /address.*
  script: main.app

- url: /scripts/angular-file-upload.min.js
  static_files: node_modules/angular-file-upload/dist/angular-file-upload.min.js
  upload: node_modules/angular-file-upload/dist/angular-file-upload.min.js

- url: /.*
  static_files: index.html
  upload: index.html

libraries:
- name: webapp2
  version: "2.5.2"
